### ISSUE TITLE
Purpose of the repo

### ISSUE THREAD

**Issue by danishjuneja** [WebClub-NITK/Hacktoberfest-2k21#15]
Whats the point of making new repos just for contribution that adds little or no value to open source dev
It kills the purpose completely right

**Comment by priyansh32** [comment]
+1

**Comment by ikjot-2605** [comment]
Hi @danishjuneja, thank you for your query!

The main purpose of this repository is to ensure that younger developers, who have just started their open source journey get some practice on the ins and outs of GitHub on an active repository, before they work on larger projects.
For further queries, take a look at our [contributing](https://github.com/WebClub-NITK/Hacktoberfest-2k21/blob/main/.github/CONTRIBUTING.md) guidelines.

Also, in the future, kindly try adhering to the issue template.
