### ISSUE TITLE
Hill Cipher

### ISSUE THREAD

**Issue by sudarshan411** [WebClub-NITK/Hacktoberfest-2k21#4]
### Description
Given a key, write a program that encrypts/decrypts a particular text using an implementation of the Hill Cypher.

### Details
 - Technical Specifications: C, C++, Python, Java, Go
 - Type of issue: Single
 - Time Limit: 1 day after the issue is assigned

### Resources
These links can help give an idea about the Hill Cipher.

 - [Wikipedia - Hill Cipher](https://en.wikipedia.org/wiki/Hill_cipher)
 - [Educative.io - Hill Cipher](https://www.educative.io/edpresso/what-is-the-hill-cipher)

### Directory Structure
Create a folder named `Hill-Cipher` in the `Systems` folder. File should be named as `hill-cipher`. This file should be added to the `Systems/Hill-Cipher` folder.  Only **one** file should be submitted and it should contain the necessary code alone.

#### Note
1. Please claim the issue first by commenting here before starting to work on it.
2. Once you are done with the task and have created a Pull Request, please tag @sudarshan411 to request a review.

**Comment by jarvis-1805** [comment]
Hi @sudarshan411, I would like to work on this issue!

**Comment by sudarshan411** [comment]
Hey @jarvis-1805! Sure you can go ahead and work on it.

@muditsinghal Could you assign the issue to @jarvis-1805?

**Comment by jarvis-1805** [comment]
Hi @muditsinghal, please assign this issue to me.

**Comment by jarvis-1805** [comment]
Hey @sudarshan411, please review pull request #28!
