### ISSUE TITLE
Grayscaling of Images

### ISSUE THREAD

**Issue by adithi-su** [WebClub-NITK/Hacktoberfest-2k21#9]
### Description
The goal is to implement your own grayscaling algorithm for this image processing project using pixel manipulation. 

### Details
- Import a colour image of your choice using the Pillow library or OpenCV and then transform the array to convert it to it's grayscaled version. For this project, you are advised to either use the Average method ( (R+G+B)/3 ) or the Luminosity method (0.21*R+0.72*G+0.07*B).
- Type of issue: Single 
- Time Limit: 2 days after assignment of the issue

### Issue requirements / progress
You are expected to submit the code in either a jupyter notebook or colab notebook.
- [ ] Import an image using Pillow or OpenCV
- [ ] Convert the colour image into a grayscale image using the Average method or Luminosity method.

### Resources
OpenCV: https://docs.opencv.org/4.5.1/d6/d00/tutorial_py_root.html  
Python Pillow: https://www.tutorialspoint.com/python_pillow/python_pillow_using_image_module.htm

### Directory Structure
Create a folder named grayscaling in the Intelligence folder and submit the jupyter notebook or colab notebook.

#### Note
1. Please claim the issue first by commenting here before starting to work on it.
2. Once you are done with the task and have created a Pull Request, please tag @adithi-su to request a review.

**Comment by sneaky-potato** [comment]
Hi, I have fair amount of experience in basic image processing using OpenCV library. I think I can do this. Could you please assign this issue to me?

**Comment by vinayakj02** [comment]
I can do this.  Could you assign this issue to me?

**Comment by adithi-su** [comment]
@sneaky-potato Sure! go ahead.

**Comment by Shivam-Shrivastav** [comment]
I have done some projects in Pillow and OpenCV, can you assign this issue to me?

**Comment by adithi-su** [comment]
@Shivam-Shrivastav you are advised to implement the algorithm using the Average method ( (R+G+B)/3 ) or the Luminosity method (0.21R+0.72G+0.07*B) and not directly use cv2.COLOR_BGR2GRAY.
